[git]
username = "your name"
email = "name@example.com"

[omz]
# https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
theme = "robbyrussell"
# https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins
plugins = ["git"]

[env]
# Keep these envs unchanged!
DISABLE_MAGIC_FUNCTIONS = "true"
HOMEBREW_BUNDLE_FILE = "~/.config/homebrew/Brewfile"
HOMEBREW_NO_AUTO_UPDATE = "true"
ELECTRON_OZONE_PLATFORM_HINT = "auto"

[alias]
hm = "home-manager"
hms = "home-manager switch --impure"
brewdump = "brew bundle dump --cask --mas --tap --describe --force"
brewup = "brew bundle install"

[home.file]
".ssh/id_ed25519.pub" = { text = "your ssh pubic key" }

[nix]
# https://search.nixos.org/packages
packages = ["fastfetch"]
